Lesson 25
delosiliana/qna pull request #2
Opened 2018-01-19 15:59 UTC by delosiliana

Реализовала создание вопроса и ответа.
Добавила тесты к ним.

2018-01-20 05:41 UTC, iBublik requested changes

2018-01-20 05:41 UTC, iBublik commented on app/controllers/questions_controller.rb
> +
В скринкасте создавался полный CRUD контроллер, не вижу у тебя этого кода

2018-01-20 05:41 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +RSpec.describe QuestionsController, type: :controller do
Тестов из скринкаста так же не хватает

2018-01-20 05:41 UTC, iBublik commented on spec/factories/answers.rb
> +    body nil
Соблюдай отступы

2018-01-20 05:41 UTC, iBublik commented on spec/factories/questions.rb
> +  factory :invalid_question, class: "Question" do
С ответами ты сделала более удобно - фабрики можно вкладывать, это некое подобие наследования. Вложенная фабрика будет иметь те же атрибуты, что и родительская (есди ты не переопределишь их). В данном случае это позволит не писать имя класса.

2018-01-21 17:45 UTC, delosiliana commented on spec/controllers/questions_controller_spec.rb
> +RSpec.describe QuestionsController, type: :controller do
@iBublik  По заданию, написано, что создавать, поэтому остальные сразу не добавила..

2018-01-21 18:24 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +RSpec.describe QuestionsController, type: :controller do
Во всех заданиях предполагается, что код ты будешь повторять код из скринкастов

2018-01-21 18:28 UTC, iBublik commented on config/routes.rb
> +    resources :answers
Лучше исключать из роутов несуществующие эндпоинты. Сейчас можно обратиться по адресу `/questions/1/answers/1/edit`, но это вызовет ошибку, т.к. в контроллере нет обработки экшна edit, и вьюхи соответствующей нет

2018-01-22 11:38 UTC, vkurennov approved these changes

2018-01-23 14:00 UTC, merged