Lesson 26
delosiliana/qna pull request #3
Opened 2018-02-08 16:09 UTC by delosiliana

Создала acceptance тесты для вопросов\ответов
Для создания и удаления. Чтобы удалять мог только пользователь создавший ресурс.
Добавила аутентификацию
Покрыла acceptance тестами вход\выход\регистрацию
Добавила просмотр вопросов любому пользователю.

2018-02-08 19:05 UTC, iBublik requested changes

2018-02-08 19:05 UTC, iBublik commented on app/controllers/answers_controller.rb
>    def new
Этот экшен больше не нужен - форма ответа находится на странице вопроса

2018-02-08 19:05 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create, :destroy]
Тут же пока нет других экшнов, так что нет смысла писать `only`

2018-02-08 19:05 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :load_answer, only: [:destroy]
Если `before_action` нужен только в одном экшене, то лучше логику в самом экшене и описать. Иначе получается размазывание

2018-02-08 19:05 UTC, iBublik commented on app/models/user.rb
> +  has_many :questions
Не забывай указывать что происходит с ресурсами при удалении (опция `dependent`)

2018-02-08 19:05 UTC, iBublik commented on app/views/layouts/application.html.erb
> +      <%= link_to 'Sign out', destroy_user_session_path(@user), method: :delete %>
Зачем тут передавать пользователя? Не может быть залогинено несколько пользователей, поэтому "уничтожить" можно только одну сессию. Ну и полагаться в главном лейауте, что где-то будет создана интсанс-переменная `@user` - так себе затея

2018-02-08 19:05 UTC, iBublik commented on app/views/questions/show.html.slim
> +  = link_to 'Delete question', question_path, method: :delete
`question_path` без параметра упадет

2018-02-08 19:05 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - if answer.persisted?
Чтоб не усложнять логику, лучше сразу итерировать только сохраненные ответы. Коллекцию подготовь в контроллере - `@answers = @question.answers.select(&:persisted?)`

2018-02-08 19:05 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +  scenario 'Authenticated user can create answer' do
Нужен тест с попыткой создания невалидного ответа. Там не забудь проверить, что выводятся ошибки валидации

2018-02-08 19:05 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'Answer text'
Нужно также проверять наличие сообщения об успешном создании ответа. Иначе этот тест пройдет, даже если ответ не сохранился (текст "Answer text" будет в форме ответа)

2018-02-08 19:05 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Authenticated user creates question' do
Нужен сценарий с попыткой создания невалидного вопроса

2018-02-08 19:05 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_no_content (answer.body)
Зачем тут пробел перед скобками?

2018-02-08 19:05 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'To delete answer which is not the author' do
Описание сценария должно быть в форме "Не автор не видит ссылки на удаление", а у тебя тут "Удалить ответ, который не автор". При прогоне тестов с опцией `--format=doc` должны получаться более менее складные предложения

2018-02-08 19:05 UTC, iBublik commented on spec/acceptance/user_can_view_question_spec.rb
> +  scenario 'User can view questions' do
Нужен отдельный файл с тестами на просмотр вопроса (и списка ответов к нему)

2018-02-08 19:05 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer in database' do
Нужен еще один тест, который проверяет привязку ответа к пользователю

2018-02-08 19:05 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: author_answer } }.to change(Answer, :count).by(-1)
Проверь, что удалился именно ответ залогиненного пользователя.

2018-02-08 19:05 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +      expect { delete :destroy, params: { id: author_question } }.to change(Question, :count).by(-1)
Тут так же нужно проверять изменение числа вопросов пользователя

2018-02-08 19:05 UTC, iBublik commented on spec/factories/questions.rb
> +  factory :invalid_question, class: Question do
А зачем было выносить эту фабрику из фабрики question?

2018-02-08 19:05 UTC, iBublik commented on spec/factories/users.rb
> +  sequence :email do |n|
Ты создала глобальную последовательность, которая будет видна и в других фабриках. Лучше так делать только с последовательностями, которые используются в нескольких фабриках. И выносить их в отдельный файл, например sequences.rb

2018-02-08 19:05 UTC, iBublik commented on spec/models/user_spec.rb
> +  describe '#author? method for question' do
Ну отдельно тестировать для вопроса и ответа я бы не стал. Там все одинаково. Но если уж тестировать, то ответ/вопрос - это контексты, а не отдельные дескрайбы

2018-02-08 19:05 UTC, iBublik commented on spec/models/user_spec.rb
> +      expect(user.author?(question)).to be true
Для методов-предикатов RSpec генерирует удобные матчеры - `expect(user).to be_author(question)`

2018-02-19 13:05 UTC, vkurennov approved these changes

2018-02-19 13:05 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully created'
Тут еще надо проверить, что ответ появился на странице

2018-02-19 13:05 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Тут также нужно проверить наличие заголовка и тела вопроса на странице

2018-02-19 13:05 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'To delete answer which is not the author' do
Не исправлено

2018-02-19 13:05 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +  scenario 'To delete question which is not the author' do
Тут и далее опять же неверные описания  сценариев. Сценарии формулируются по принципу "роль пользователя может/не может выполнить действие при таких-то условиях"

2018-02-19 13:05 UTC, vkurennov commented on spec/models/user_spec.rb
> +  context '#author? method for answer' do
У тебя метод универсальный, он будет работать с любым объектом, у которого есть user_id, поэтому не нужно проверять на каждом типе аргумента.

2018-02-19 13:05 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author?(question)).to be true
Есть более интересный синтаксиси для методов-предиктов: `expect(user).to be_author(question)`, т.е. вызхов метода переносим после to, добавляем к нему be_ и убираем знак вопроса.

2018-02-22 15:05 UTC, merged